"""Image generation and editing: the generate_image / edit_image tools, delivery
of generated bytes as an upload, and the chat-action keepalive.

The image endpoint and Telegram downloads are faked at the imagegen module
seam; the contract under test is what the tools queue, what Telegram is
handed, and what lands in memory."""

import asyncio
from datetime import datetime, timezone
from types import SimpleNamespace

import pytest
from aiogram.types import BufferedInputFile
from sqlalchemy import select

from app.agents.deps import AgentDeps
from app.agents.models import probe_image
from app.agents.runtime import execute_run
from app.agents.tools import MAX_RUN_ATTACHMENTS, edit_image, generate_image
from app.core.crypto import encrypt
from app.media import imagegen
from app.memory.embeddings import FakeEmbedder
from app.models import (
    AgentRun,
    Bot,
    Chat,
    ConnectedModel,
    Message,
    MessageAttachment,
    ModelRoleAssignment,
)
from app.telegram.limiter import SendLimiter
from app.telegram.media import OutgoingMedia

from tests.test_agent import authorize_chat
from tests.test_agent_media import MediaFakeBot, run_agent_with, seed_media_messages
from tests.test_handlers import message_update, run_update

PNG = b"\x89PNG\r\n\x1a\nfake-image"


@pytest.fixture
async def bot_row(db_sessionmaker):
    async with db_sessionmaker() as s:
        row = Bot(
            tg_bot_id=999,
            username="convoke_bot",
            name="ConvokeBot",
            token_encrypted=encrypt("123:fake"),
            can_read_all_group_messages=True,
        )
        s.add(row)
        await s.commit()
        return row


async def add_image_model(db_sessionmaker):
    async with db_sessionmaker() as s:
        m = ConnectedModel(
            name="image-model", base_url="http://unused", model_name="gpt-image-test",
            capabilities={"image": True},
        )
        s.add(m)
        await s.flush()
        s.add(ModelRoleAssignment(role="image", model_id=m.id))
        await s.commit()


class FakeImageAPI:
    """Stands in for the image endpoint + Telegram downloads; records calls."""

    def __init__(self, monkeypatch, fail: Exception | None = None, delay: float = 0):
        self.calls: list[tuple] = []
        self.fail = fail
        self.delay = delay
        monkeypatch.setattr(imagegen, "generate", self.generate)
        monkeypatch.setattr(imagegen, "edit", self.edit)
        monkeypatch.setattr(imagegen, "download_chat_files", self.download)

    async def _finish(self):
        if self.delay:
            await asyncio.sleep(self.delay)
        if self.fail is not None:
            raise self.fail
        return PNG

    async def generate(self, provider, prompt, size=None):
        self.calls.append(("generate", provider.model_name, prompt, size))
        return await self._finish()

    async def edit(self, provider, images, prompt, size=None):
        self.calls.append(("edit", provider.model_name, images, prompt, size))
        return await self._finish()

    async def download(self, session, chat_id, file_ids):
        self.calls.append(("download", file_ids))
        return [f"bytes:{f}".encode() for f in file_ids]


async def make_ctx(db_sessionmaker, bot_row):
    chat = await authorize_chat(db_sessionmaker, MediaFakeBot(), bot_row)
    await seed_media_messages(db_sessionmaker, chat.id)
    deps = AgentDeps(sessionmaker=db_sessionmaker, embedder=FakeEmbedder(),
                     chat_id=chat.id, run_id=1)
    return chat, SimpleNamespace(deps=deps)


async def test_generate_image_tool(db_sessionmaker, bot_row, monkeypatch):
    api = FakeImageAPI(monkeypatch)
    chat, ctx = await make_ctx(db_sessionmaker, bot_row)

    # no image role assigned → actionable refusal, nothing generated
    out = await generate_image(ctx, "a frog in a top hat")
    assert "no image model is assigned" in out
    assert api.calls == [] and ctx.deps.media == []

    await add_image_model(db_sessionmaker)
    assert "Pass a prompt" in await generate_image(ctx, "  ")

    out = await generate_image(ctx, " a frog in a top hat ", orientation="landscape")
    assert "Generated the image" in out
    assert api.calls == [("generate", "gpt-image-test", "a frog in a top hat", "1536x1024")]
    assert ctx.deps.media == [OutgoingMedia(
        kind="photo", source="generated", data=PNG, described=True,
        description="Image the bot generated. Prompt: a frog in a top hat",
    )]
    assert ctx.deps.generating == 0

    # no orientation → the size parameter is omitted (model chooses)
    await generate_image(ctx, "a pond at dusk")
    assert api.calls[-1][3] is None


async def test_generate_image_failure_and_cap(db_sessionmaker, bot_row, monkeypatch):
    api = FakeImageAPI(
        monkeypatch, fail=imagegen.ImageGenError("HTTP 400: rejected by the safety system")
    )
    chat, ctx = await make_ctx(db_sessionmaker, bot_row)
    await add_image_model(db_sessionmaker)

    # the provider's reason reaches the agent; nothing is queued
    out = await generate_image(ctx, "something disallowed")
    assert "generation failed" in out and "safety system" in out
    assert ctx.deps.media == [] and ctx.deps.generating == 0

    # unexpected errors are reported by type only
    api.fail = RuntimeError("secret internals")
    out = await generate_image(ctx, "x")
    assert "RuntimeError" in out and "secret" not in out

    # a full reply is refused BEFORE paying for a generation
    api.fail = None
    api.calls.clear()
    ctx.deps.media.extend(
        OutgoingMedia(kind="photo", source="url", url=f"https://x.test/{i}.jpg")
        for i in range(MAX_RUN_ATTACHMENTS)
    )
    assert "Attachment limit reached" in await generate_image(ctx, "one more")
    assert api.calls == []


async def test_edit_image_tool_validation(db_sessionmaker, bot_row, monkeypatch):
    api = FakeImageAPI(monkeypatch)
    chat, ctx = await make_ctx(db_sessionmaker, bot_row)
    await add_image_model(db_sessionmaker)
    async with db_sessionmaker() as s:
        # #11: a PNG sent as a file; #12: a HEIC file the endpoint can't take;
        # #13: an oversize photo
        for tg, kw in (
            (11, dict(kind="image_document", mime="image/png")),
            (12, dict(kind="image_document", mime="image/heic")),
            (13, dict(kind="photo", size_bytes=50 * 2**20)),
        ):
            m = Message(chat_id=chat.id, tg_message_id=tg, sender_name="Alice", text="",
                        sent_at=datetime(2026, 7, 1, tzinfo=timezone.utc))
            s.add(m)
            await s.flush()
            s.add(MessageAttachment(message_id=m.id, chat_id=chat.id, tg_message_id=tg,
                                    file_id=f"F{tg}", file_unique_id=f"u{tg}",
                                    status="described", **kw))
        await s.commit()

    assert "no media" in await edit_image(ctx, [1], "make it pop")
    assert "only photos" in await edit_image(ctx, [6], "make it pop")  # video
    assert "only photos" in await edit_image(ctx, [12], "make it pop")  # HEIC
    assert "history import" in await edit_image(ctx, [3], "make it pop")
    assert "too large" in await edit_image(ctx, [13], "make it pop")
    assert "not in Convoke's stored history" in await edit_image(ctx, [99], "make it pop")
    # unmonitored thread reads exactly like a missing id
    assert "not in Convoke's stored history" in await edit_image(ctx, [7], "make it pop")
    assert "at least one" in await edit_image(ctx, [], "make it pop")
    assert "At most" in await edit_image(ctx, list(range(100, 109)), "make it pop")
    assert "Pass an instruction" in await edit_image(ctx, [2], " ")
    # one bad source rejects the whole edit before anything is downloaded
    assert "no media" in await edit_image(ctx, [2, 1], "combine")
    assert api.calls == [] and ctx.deps.media == []

    # happy path: sources downloaded in order (duplicates dropped), sent with
    # their mime types, result queued with a description naming the sources
    out = await edit_image(ctx, [2, 11, 2], "put them on one beach", orientation="portrait")
    assert "Edited the image" in out
    assert api.calls == [
        ("download", ["F2", "F11"]),
        ("edit", "gpt-image-test",
         [(b"bytes:F2", "image/jpeg"), (b"bytes:F11", "image/png")],
         "put them on one beach", "1024x1536"),
    ]
    assert ctx.deps.media[0].description == (
        "Image the bot edited from #2, #11. Instruction: put them on one beach"
    )
    assert ctx.deps.media[0].data == PNG and ctx.deps.generating == 0


async def test_execute_run_uploads_generated_image(db_sessionmaker, bot_row, monkeypatch):
    FakeImageAPI(monkeypatch)
    await add_image_model(db_sessionmaker)
    fake = MediaFakeBot()
    chat, run_id = await run_agent_with(
        db_sessionmaker, bot_row, fake, monkeypatch,
        [("generate_image", {"prompt": "a frog knight"})],
        request="@convoke_bot draw a frog knight",
    )

    async with db_sessionmaker() as s:
        run = await s.get(AgentRun, run_id)
        assert run.status == "done", run.error
        assert run.media == [{"kind": "photo", "source": "generated", "ok": True}]

    # text first, then the bytes go up as an upload (not a file_id/URL)
    assert [e[0] for e in fake.events[-2:]] == ["text", "photo"]
    sent = fake.events[-1][1]
    assert isinstance(sent, BufferedInputFile) and sent.data == PNG

    # persisted as the bot's own photo, already described with the prompt —
    # MediaLoop never runs vision on it, and attach/edit can reuse its file_id
    async with db_sessionmaker() as s:
        att = (
            await s.execute(
                select(MessageAttachment)
                .join(Message, Message.id == MessageAttachment.message_id)
                .where(Message.source == "self")
            )
        ).scalar_one()
        assert att.status == "described"
        assert att.description == "Image the bot generated. Prompt: a frog knight"
        assert att.file_id.startswith("sentF")


async def test_generated_image_survives_url_drop(db_sessionmaker, bot_row, monkeypatch):
    """A rejected album with a URL item retries without the URL — generated
    uploads stay in the retry like history items do."""
    from tests.test_agent_media import bad_request

    FakeImageAPI(monkeypatch)
    await add_image_model(db_sessionmaker)
    fake = MediaFakeBot()

    def arm():
        fake.fail_media = bad_request()
        fake.fail_media_once = True

    chat, run_id = await run_agent_with(
        db_sessionmaker, bot_row, fake, monkeypatch,
        [("attach_media_url", {"url": "https://pics.test/broken.jpg"}),
         ("generate_image", {"prompt": "a frog"}),
         ("attach_media", {"message_id": 2})],
        arm=arm,
    )
    async with db_sessionmaker() as s:
        run = await s.get(AgentRun, run_id)
        assert run.media == [
            {"kind": "photo", "source": "url", "ok": False},
            {"kind": "photo", "source": "generated", "ok": True},
            {"kind": "photo", "source": "history", "ok": True},
        ]
    group = [e for e in fake.events if e[0] == "group"][-1][1]
    assert isinstance(group[0], BufferedInputFile) and group[1] == "F2"


async def test_chat_action_kept_alive_and_stopped(db_sessionmaker, bot_row, monkeypatch):
    import app.agents.runtime as runtime

    monkeypatch.setattr(runtime, "CHAT_ACTION_INTERVAL_S", 0.01)
    FakeImageAPI(monkeypatch, delay=0.1)  # generation long enough for several ticks
    await add_image_model(db_sessionmaker)
    fake = MediaFakeBot()
    await run_agent_with(
        db_sessionmaker, bot_row, fake, monkeypatch,
        [("generate_image", {"prompt": "a frog"})],
    )
    # first "typing" is sent inline, then "sending photo…" while generating
    assert fake.actions[0] == "typing"
    assert "upload_photo" in fake.actions
    # the loop dies with the run — no actions after the reply landed
    n = len(fake.actions)
    await asyncio.sleep(0.05)
    assert len(fake.actions) == n


async def test_probe_image_unreachable_fails():
    ok, detail = await probe_image("http://127.0.0.1:9/v1", "gpt-image", None)
    assert not ok and "Couldn't reach" in detail



async def test_chat_action_targets_forum_general_topic(db_sessionmaker, bot_row, monkeypatch):
    """General-topic messages carry no thread id, but a chat action without
    one isn't displayed in a forum's General — it must name topic 1, while
    the reply itself still omits it."""
    fake = MediaFakeBot()
    await run_agent_with(db_sessionmaker, bot_row, fake, monkeypatch, [])
    assert fake.action_threads == [None]  # non-forum chat: no topic id

    async with db_sessionmaker() as s:
        chat = (await s.execute(select(Chat))).scalar_one()
        chat.is_forum = True
        await s.commit()
    fake.action_threads.clear()
    await run_update(db_sessionmaker, fake, bot_row, message_update(4, 21, "@convoke_bot again"))
    async with db_sessionmaker() as s:
        run_id = (
            await s.execute(select(AgentRun.id).where(AgentRun.status == "pending"))
        ).scalar_one()
    await execute_run(db_sessionmaker, FakeEmbedder(), SendLimiter(), fake, run_id)
    assert fake.action_threads == [1]
    reply = [e for e in fake.events if e[0] == "text"][-1]
    assert reply[2].get("message_thread_id") is None
